spring:
  application:
    name: urlshortener
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/practiceDB
    username: postgres
    password: postgresroot
  jpa:
    hibernate:
      ddl-auto: update